In [ ]:
# NIM/Nama	  	: 16520002/Eraraya Morenzo Muten
# Tanggal	  	  : 16 Desember 2020
# Shift/Kelas	  : 3.1/A

# Problem 2

Import Library

In [1]:
import pandas as pd

Membaca File CSV

In [3]:
# membaca file csv pada directory yang sama dengan notebook ini sebagai DataFrame Pandas
df = pd.read_csv('nilai_uas.csv')

Nomor 1

In [ ]:
# menyimpan posisi baris nilai Tuan Mor pada kolom nama
idx = df.index[df['nama']=='Tuan Mor'][0]

# menampilkan nilai kalkulus, fisika, dan kimia Tuan Mor
print("Nilai kalkulus Tuan Mor adalah",df['nilai_kal'][idx])
print("Nilai fisika Tuan Mor adalah",df['nilai_fis'][idx])
print("Nilai kimia Tuan Mor adalah",df['nilai_kim'][idx])

# Nilai kalkulus Tuan Mor adalah 94.76
# Nilai fisika Tuan Mor adalah 67.5
# Nilai kimia Tuan Mor adalah 24.82

Nilai kalkulus Tuan Mor adalah 94.76
Nilai fisika Tuan Mor adalah 67.5
Nilai kimia Tuan Mor adalah 24.82

Nomor 2

In [ ]:
# menyimpan nilai fisika tertinggi
nilai_fis_max = df['nilai_fis'].max()
# menyimpan posisi-posisi baris nilai fisika tertinggi tersebut
idx = df.index[df['nilai_fis']==nilai_fis_max]
# menampilkan semua nama yang memiliki nilai fisika tertinggi tersebut
print("Mahasiswa dengan nilai fisika tertinggi adalah:")
for i in idx:
  print(df['nama'][i])

# Mahasiswa dengan nilai fisika tertinggi adalah Cahyani Mora

Mahasiswa dengan nilai fisika tertinggi adalah Cahyani Mora

Nomor 3

In [8]:
# mengurutkan DataFrame berdasarkan nilai kolom nilai kimia dari yang tertinggi ke terrendah
df_nilai_kim = df.sort_values(by = ['nilai_kim'], ascending = False).reset_index()

# menampilkan 10 mahasiswa dengan nilai kimia tertinggi
print("Sepuluh mahasiswa/mahasiswi dengan nilai kimia tertinggi adalah:")
for i in range(10):
  print(df_nilai_kim['nama'][i])

# Sepuluh mahasiswa/mahasiswi dengan nilai kimia tertinggi adalah:
# Muhammadi Jumhur
# Grace Yoga
# Maria Manurung
# Dhiya Wafa
# Rasyid FH
# Sukma Ulhaq
# Rizam Rayhan
# WIJAYANTI Amadio
# Jevon Tangguh
# Ediva zilva

Sepuluh mahasiswa/mahasiswi dengan nilai kimia tertinggi adalah:
Muhammadi Jumhur
Grace Yoga
Maria Manurung
Dhiya Wafa
Rasyid FH
Sukma Ulhaq
Rizam Rayhan
WIJAYANTI Amadio
Jevon Tangguh
Ediva zilva

Nomor 4

In [ ]:
# menampilkan banyaknya nilai kalkulus di bawah 50
print("Banyaknya nilai kalkulus di bawah 50 adalah", sum(df['nilai_kal']<50))

# Banyaknya nilai kalkulus di bawah 50 adalah 1549

Banyaknya nilai kalkulus di bawah 50 adalah 1549

Nomor 5

In [ ]:
# menampilkan banyaknya mahasiswa FMIPA
print("Banyaknya mahasiswa FMIPA adalah", sum(df['fakultas']=='FMIPA'))

# Banyaknya mahasiswa FMIPA adalah 396

Banyaknya mahasiswa FMIPA adalah 396